require('user.lazy')
require('user.config')
require('user.ui')
require('user.tabsAndStatusline')
require('user.lspConfig')
require("user.treesitter")
require("user.comment-config")
require("user.snippets")
require("user.utils")
require("user.navic-config")
require("user.dressing-config")
require("user.dap-config")
require("user.fileExplorer")
require('user.git')
-- require('user.ufo')
require('user.formatter-config')
require('user.ownFunctions')
require('user.autoComplete')
require('user.telescope')
-- require('user.prueba')
